#!/bin/sh

# 브랜치 이름 가져오기
BRANCH_NAME=$(git symbolic-ref --short HEAD)
TICKET_NUMBER=""

# 브랜치 이름에서 Jira 티켓 번호 추출 (예: abc-123)
if [[ $BRANCH_NAME =~ ^[a-zA-Z]+-[0-9]+ ]]; then
    TICKET_NUMBER=$(echo $BRANCH_NAME | grep -oE '[a-zA-Z]+-[0-9]+')
fi

# 커밋 메시지에 티켓 번호 추가
if [ -n "$TICKET_NUMBER" ]; then
    echo "$TICKET_NUMBER $(cat $1)" > $1
fi
